"""empty message

Revision ID: 92afc8158d15
Revises: 4e9d05eaaf38
Create Date: 2022-04-04 23:18:03.854337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92afc8158d15'
down_revision = '4e9d05eaaf38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
