"""empty message

Revision ID: 9379ae436fde
Revises: 
Create Date: 2022-04-03 06:02:23.067231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9379ae436fde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('api_token', sa.String(length=35), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('book',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('publisher', sa.String(length=50), nullable=True),
    sa.Column('publish_year', sa.String(length=50), nullable=True),
    sa.Column('categories', sa.String(length=50), nullable=True),
    sa.Column('stock', sa.Float(precision=2), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    op.drop_table('user')
    # ### end Alembic commands ###
